// whitelistAndFetchProxy.js
import dotenv from 'dotenv';
import axios from 'axios';
import fs from 'fs/promises';
dotenv.config();

const KEY = process.env.TWOCAPTCHA_API_KEY;

if (!KEY) {
    console.error('❌ Please set TWOCAPTCHA_API_KEY in your environment or .env');
    process.exit(1);
}

async function getPublicIp() {
    try {
        const r = await axios.get('https://api.ipify.org?format=json', { timeout: 10000 });
        return r.data.ip;
    } catch (err) {
        // fallback to user-provided env IP if available
        if (process.env.MY_PUBLIC_IP) return process.env.MY_PUBLIC_IP;
        throw err;
    }
}

async function generateWhitelistProxy(ip, country = 'us', protocol = 'http', connection_count = 1) {
    if (!ip) throw new Error('Missing IP address!');

    const endpoint = 'https://api.2captcha.com/proxy/generate_white_list_connections';
    const query = `key=${KEY}&ip=${ip}&country=${country}&protocol=${protocol}&connection_count=${connection_count}`;
    const url = `${endpoint}?${query}`;

    console.log('📡 Requesting proxy with URL:');
    console.log(url);

    try {
        const res = await axios.get(url, {
            timeout: 15000,
            headers: {
                'Accept': 'application/json',
            }
        });

        // Debug full response
        console.log('📨 Raw response data:', res.data);

        if (res.data && res.data.status === 1 && Array.isArray(res.data.connections)) {
            return res.data;
        }

        throw new Error('Unexpected 2Captcha response: ' + JSON.stringify(res.data));
    } catch (err) {
        const msg = err.response?.data || err.message || String(err);
        throw new Error('Failed to get proxy from 2Captcha: ' + JSON.stringify(msg).slice(0, 500));
    }
}

async function main() {
    try {
        console.log('🔎 Detecting public IP...');

        const ip = await getPublicIp();
        console.log('📡 Public IP detected:', ip);
        if (!ip || !/^\d{1,3}(\.\d{1,3}){3}$/.test(ip)) {
            throw new Error(`❌ Invalid IP: ${ip}`);
        }


        console.log('🛂 Generating whitelist connection(s) for IP via 2Captcha...');
        const resp = await generateWhitelistProxy(ip, 'us', 'http', 1);

        // resp example on success:
        // { status: 1, connections: ["us5.proxy.2captcha.com:8080"], ... }
        console.log('📨 Raw API response:', resp);

        if (!resp.connections || !Array.isArray(resp.connections) || resp.connections.length === 0) {
            console.error('⚠️ No connections returned. Response:', resp);
            process.exit(2);
        }

        const conns = resp.connections;
        console.log('✅ Received proxy connections:');
        conns.forEach((c, i) => console.log(`  [${i}] ${c}`));

        // Save to .proxy.env for easy reuse
        const out = `# Generated by whitelistAndFetchProxy.js\nPROXY_CONNECTIONS=${JSON.stringify(conns)}\nPROXY=${conns[0]}\n`;
        await fs.writeFile('.proxy.env', out, 'utf8');
        console.log('💾 Saved to ./.proxy.env (PROXY and PROXY_CONNECTIONS)');

        // Helpful usage hint
        console.log('\n📌 Example Playwright usage (no username/password — whitelist mode):');
        console.log(`proxy.server = 'http://${conns[0]}'`);
        console.log('Use the same proxy string for the 2Captcha solver call (proxy: "http://<host:port>")');

        console.log('\n🎉 Done.');
    } catch (err) {
        console.error('❌ Error:', err.message || err);
        process.exit(1);
    }
}

main();
